---
    - name : simple playbook for webserver
      hosts : webserver
      gather_facts: no
      vars_files:
       - group_vars/webserver.yml
      tasks :

      # check if httpd are there 
        - name: httpd and firewalld are present
          yum :
            name: "{{item}}"
            state: present
          loop: "{{service}}"

      # install httpd 
        - name: install httpd and firewalld
          yum: 
            name: "{{item}}"
            update_cache: yes 
            state: latest
          loop: "{{service}}"
      # enable httpd 
        - name: httpd is enabled
          service:
             name: "{{service[0]}}"
             state: started
             enabled: true 

      # enable NTP 
        - name: NTP server is enabled
          service:
             name: chronyd 
             enabled: true
          when: time is defined 

      # copy html file to the server 
        - name: index.html is present 
          become: false
          copy:
            src: ./index.html
            dest: /var/www/html/index.html
      # permit access to httpd service 
        - name: firewalld permits access to httpd service 
          firewalld:
            service: "{{rule}}"
            permanent: true
            state: enabled
            immediate: yes