---
    - name : simple playbook for DBServer
      hosts : dbserver
      vars_files:
       - host_vars/user.yml
       - group_vars/dbserver.yml
       

      tasks:

      # install mariadb 
      - name: install {{db_pkg}}
        yum:
         name: "{{db_pkg}}"
         state: latest 
      # add python MySQL support
      - name: adding Python MySQL Support 
        pip: 
          name: MySQL-python
     


      # enable mariadb
      - name: mariadb enabled and running
        service:
          name: mariadb
          state: started
          enabled: true

      - name: Set the root Password
        mysql_user:
            login_user: root
            login_password: ""
            user: root
            password: "{{mysql_root_password}}"
            host: localhost
          
      - name: Delete anonymous Mysql server user
        mysql_user:
          user: ""
          state: absent

      - name: Remove the test database for Mysql
        mysql_db:
          db: test
          state: absent

