---
    - name : simple playbook for DBServer
      hosts : dbserver
      vars_files:
       - host_vars/user.yml
       - group_vars/dbserver.yml
       

      tasks:

      # install mariadb 
      - name: install {{db_pkg}}
        yum:
         name: "{{db_pkg}}"
         state: latest 
      # add python MySQL support
      - name: adding Python MySQL Support 
        yum:
          name: python3-PyMySQL
     


      # enable mariadb
      - name: mariadb enabled and running
        service:
          name: mariadb
          state: started
          enabled: true

      - name: Set the root Password
        mysql_user:
            name: root
            login_password: "{{mysql_root_password}}"
            password: "{{mysql_root_password}}"
            when: mysql_root_password is defined
          
      - name: Delete anonymous Mysql server user
        mysql_user:
          user: ""
          login_password: "{{mysql_root_password}}"
          state: absent

      - name: Remove the test database for Mysql
        mysql_db:
          login_password: "{{mysql_root_password}}"
          db: test
          state: absent

      - name: create a new user for mariadb 
        mysql_user:
          name: "nalomari"
          password: "{{dbUser_password}}"
          login_password: "{{mysql_root_password}}"
          priv: '*.*:ALL'
          state: present


